# -*- coding: utf-8 -*-
"""Funciones Ajuste.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-g3eq0WeH5AUiHvsqRLCTZOq6M91uQzu
"""

def detectar_outliers(lista_columnas, dataframe): 
    
    dicc_indices = {} 
    dicc_ceros = {}

    for col in lista_columnas:
        
        
        Q1 = np.nanpercentile(dataframe[col], 25)
        Q3 = np.nanpercentile(dataframe[col], 75)
        
       
        IQR = Q3 - Q1
        
       
        outlier_step = 1.5 * IQR
        
     
        outliers_data = dataframe[(dataframe[col] < Q1 - outlier_step) | (dataframe[col] > Q3 + outlier_step)] 
        
        if outliers_data.shape[0] > 0:

          dicc_indices[col] = (list(outliers_data.index))        

    
    return dicc_indices

"""A esta función le pasamos el listado de columnas por el cual tiene que iterar y el dataframe sobre el cual ha de aplicarse.

Tras ello, definimos el rango intercuartílico y lo que sería un outlier y le pedimos que busque aquellas filas que contienen outliers y nos las devuelva en un diccionario donde almacenamos estos índices para posteriormente poder tratar los outliers.
"""

